Adding Alias
bernardoVale/ansible-role-db2 pull request #39
Opened 2017-11-28 17:35 UTC by torbenbru

Reffering to #38 .

2017-11-28 19:44 UTC, bernardoVale requested changes

2017-11-28 19:44 UTC, bernardoVale commented on library/db2
> +	self.alias = self.module.params['alias']
Can you please fix the spaces?

2017-11-28 19:44 UTC, bernardoVale commented on examples/databases.yml
> +	   alias: other
Here too :)

2017-11-28 19:44 UTC, bernardoVale commented on library/db2
> +	    alias=dict(required=False, default=None, type='str'),
and here

2017-11-28 20:52 UTC, torbenbru commented
Sure no Idea how the spaces got there..

2017-11-28 23:34 UTC, bernardoVale commented on library/db2
> +	options += "alias %s " % db.alias
Indentation error :/

2017-11-29 18:25 UTC, torbenbru commented
Sorry Github really seems to be buggy with intends for me.. Can you fix this maybe?

2017-11-29 19:22 UTC, bernardoVale commented
This has nothing to do with Github. Please open the file with a text editor and fix the space issues. Python language is oriented by indentation.

2017-11-30 17:02 UTC, closed without merging